# Generated by Django 4.2 on 2025-11-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('director_name', models.CharField(max_length=30)),
                ('year_realase', models.DateField()),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
            ],
        ),
    ]
